### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by TinoGuo** [Super-Crab/FlutterLearn#1]
Unable to build aar. 
```
* What went wrong:
A problem occurred configuring project ':packflutter'.
> Process 'command 'unZip'' finished with non-zero exit value 9

```
Can you post more detail build process?

**Comment by Super-Crab** [comment]
@TinoGuo  这个属于命令没找到,不知道这边的编译用的是Mac还是win

**Comment by TinoGuo** [comment]
@Super-Crab 我这边用的是Mac，后来我自己改了下，可以编译了，但是产物没办法用就放弃

**Comment by Super-Crab** [comment]
@TinoGuo  这个Readme没有更新,你先执行package.sh 生成产物,然后再打aar.README中的还是旧版本的打包方式,package.sh中的是1.0版本的,有问题可以联系我

**Comment by yinhaijiao** [comment]
@Super-Crab 你好，我也是出现了这个问题。请问需要怎么修改？
我打了下详细信息，出现了这个
> caution: filename not matched:  *.dat

我用的是Mac。

**Comment by TinoGuo** [comment]
目前我是用官方的方法实现的

**Comment by Super-Crab** [comment]
@yinhaijiao @TinoGuo  谢谢两位的反馈，问题已经定位到了，因为我在用AS打开android之前先执行了根目录下的package.sh 文件，生成了flutter产物以及jar，所以unzip没有问题，你们可以尝试在命令行中执行下package.sh，注意将第七行中flutter.jar的地址设置到本地按照的flutter的地址，上面这个问题我近期修复下

**Comment by TinoGuo** [comment]
@Super-Crab 嗯，谢谢，目前还是以官方的先用着了
